language: node_js
node_js:
- "node"
cache: yarn
before_install:
- yarn global add makeshift && makeshift -r https://registry.npmjs.org
install:
- yarn install
script:
- yarn build
deploy:
  - provider: npm
    skip_cleanup: true
    email: kchau@microsoft.com
    api_key: $NPM_TOKEN
    tag: latest
    on:
      tags: true